# Generated by Django 5.0.14 on 2026-04-17 01:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=10)),
                ('quarter', models.CharField(db_index=True, max_length=7)),
                ('source', models.CharField(default='alphavantage', max_length=50)),
                ('call_date', models.DateField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('raw_text', models.TextField()),
                ('normalized_text', models.TextField()),
                ('fetched_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('source', 'symbol', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='TranscriptTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_index', models.PositiveIntegerField()),
                ('speaker', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField()),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='transcripts.transcript')),
            ],
            options={
                'ordering': ['turn_index'],
                'unique_together': {('transcript', 'turn_index')},
            },
        ),
    ]
