# Generated by Django 5.0.14 on 2026-04-18 23:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transcripts', '0002_transcriptchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('prompt_version', models.CharField(default='v1', max_length=20)),
                ('content', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='transcripts.transcript')),
            ],
            options={
                'unique_together': {('transcript', 'artifact_type', 'model', 'prompt_version')},
            },
        ),
    ]
